export const EDITOR_PROPERTY_PATHS: Record<string, readonly (readonly PropertyKey[])[]> = {
  'Activated by Capture Zone': [['Nr']],
  'Angle': [['angle']],
  'Angular Damping': [['angularDamping']],
  'Apply Force: X': [['Dr']],
  'Apply Force: Y': [['Lr']],
  'Apply Torque': [['Ur']],
  'Attach body ID': [['vl']],
  'Blue Team Uses': [['Qn', 3]],
  'Bounciness': [['restitution']],
  'Bullet': [['bullet']],
  'Bullet Density': [['bullet', 'density']],
  'Bullet Explosion Radius': [['bullet', 'M']],
  'Bullet hit damage': [['bullet', 'g']],
  'Bullet Homing Speed': [['bullet', 'S']],
  'Bullet Max Age': [['bullet', 'm']],
  'Bullet Size': [['bullet', 'u']],
  'Bullet Speed': [['bullet', 'o']],
  'Bullets Bounce': [['bullet', 'T']],
  'Capture Time': [['Vu']],
  'Circle Radius': [['ra']],
  'Collide Category': [['Gr']],
  'Collide connected': [['collideConnected']],
  'Collide with A': [['Hr']],
  'Collide with B': [['zr']],
  'Collide with C': [['Yr']],
  'Collide with D': [['qr']],
  'Collide with Players': [['Vr']],
  'Collide with Rockets': [['Kr']],
  'Connect to': [['Da']],
  'Density': [['density']],
  'Distance Damping': [['ja']],
  'Distance Length': [['Wa']],
  'Draw Line': [['Ha']],
  'FFA Uses': [['Qn', 1]],
  'Fire Rate': [['Cl']],
  'Fixed Rotation': [['fixedRotation']],
  'Force Zone': [['Ar']],
  'Force Zone: X': [['Or']],
  'Force Zone: Y': [['Rr']],
  'Freeze players': [['Xr']],
  'Friction': [['friction']],
  'Health': [['Nl'], ['qe']],
  'Initial Spawn Time': [['Hu']],
  'Invisible': [['Qr']],
  'Kill players': [['_r']],
  'Linear Damping': [['linearDamping']],
  'Motion Type': [['Pr']],
  'Motor Max Speed': [['motorSpeed']],
  'Motor Power': [['Ja']],
  'Motor Type': [['za']],
  'No Jump': [['Zr']],
  'No Physics (Scenery)': [['Jr']],
  'Objective': [['sa']],
  'Objective Target': [['ha']],
  'Offset X': [['x']],
  'Offset Y': [['y']],
  'Other Body ID': [['Da']],
  'Override Density': [['density']],
  'Parallax Amount': [['$r']],
  'Quantity': [['Gu']],
  'Range': [['range']],
  'Red Team Uses': [['Qn', 2]],
  'Respawn Time': [['zu']],
  'Sequence ID': [['Mr']],
  'Spring Strength': [['Ua']],
  'Starting Angular Velocity': [['angularVelocity']],
  'Starting X Velocity': [['o']],
  'Starting Y Velocity': [['l']],
  'Team': [['N']],
  'Unaffected by abilities/weapons': [['ia']],
  'Width': [['width']],
  'Wrap Position': [['Er']],
  'X': [['x']],
  'X Position': [['x']],
  'Y': [['y']],
  'Y Position': [['y']],
  'Z Index': [['zIndex']],
};
